image: node:18.14.2
pipelines:
  default:
    - step:
        name: Application Build
        script:
          - cd frontend
          - npm install
          - npm run build
    - step:
        name: Install netlify CLI
        script:
          - npm install -g netlify-cli
    - step:
        name: Deploy frontend application
        script: 
          - netlify deploy --prod --dir=./build --auth=$NETLIFY_AUTH_TOKEN --site=$NETLIFY_SITE_ID
