image: node:18.14.2
pipelines:
  default:
    - step:
        name: Build Frontend
        script:
          - cd frontend          
          - git archive --format=tar.gz main -o frontend-app.zip
        artifacts:
          - frontend/frontend-app.zip
    - step:
        name: Deploy to Heroku
        deployment: production
        script:
          - curl -H "Content-Type: application/zip"  -H "Authorization: Bearer $NETLIFY_AUTH_TOKEN --data-binary frontend/frontend-app.zip  https://api.netlify.com/api/v1/sites/PicwiseTeam.netlify.app/deploys