image: node:18.14.2
pipelines:
  default:
    - step:
        name: Build and Test Frontend
        script:
          - cd frontend
          - npm cache clean --force
          - rm -rf node_modules
          - rm -rf *package-lock.json
          - npm install
          - npm run build
          - tar -czvf build.tar.gz dist
        artifacts:
          - frontend/build.tar.gz
    - step:
        name: Deploy to Heroku
        script:
        - pipe: atlassian/heroku-deploy:2.1.0
          variables:
            HEROKU_API_KEY: $H_API_KEY
            HEROKU_APP_NAME: $H_APP_NAME
            ZIP_FILE: "frontend/build.zip"