image: node:18.14.2
pipelines:
  default:
    - step:
        name: Build and Test Frontend
        script:
          - cd frontend
          - npm cache clean --force
          - rm -rf node_modules
          - rm -rf *package-lock.json
          - npm install
          - npm run build
          - tar -czvf build.tar.gz dest
        artifacts:
          - frontend/build.tar.gz

    - step:
        name: Deploy to Heroku
        deployment: production
        script:
          - pipe: atlassian/heroku-deploy:1.2.2
            variables:
              HEROKU_API_KEY: $H_API_KEY
              HEROKU_APP_NAME: $H_APP_NAME
              HEROKU_EMAIL: $H_EMAIL
              ZIP_FILE: "frontend/build.zip"