image: node:10.15.0
pipelines:
  default:
    - step:
        name: Build and Test Frontend
        script:
          - cd frontend
          - npm install
          - npm run build
        artifacts:
          - frontend/build/**
    - step:
        name: test
        script:
          - echo "Finished"