image: node:18.14.2
pipelines:
  default:
    - step:
        name: Build and Test Frontend
        script:
          - cd frontend
          - npm cache clean --force
          - rm -rf node_modules
          - npm install
          - npm run build
        artifacts:
          - frontend/dest/**
    - step:
        name: test
        script:
          - echo "Finished"