image: node:18.14.2
pipelines:
  default:
    - step:
        name: Build Frontend
        script:
          - cd frontend          
          - npm install -g netlify-cli
          - npm install
          - npm run build
          - netlify deploy --dir=./build --auth=${{ env.NETLIFY_AUTH_TOKEN }} --site=$NETLIFY_SITE_ID
