image: node:18.14.2
pipelines:
  default:
    - step:
        name: Build and Test Frontend
        script:
          - cd frontend
          - git archive --format=tar.gz main -o frontend-app.tar.gz
        artifacts:
          - frontend/frontend-app.tar.gz
    - step:
        name: Deploy to Heroku
        deployment: production
        script:
          - pipe: atlassian/heroku-deploy:2.1.0
            variables:
              HEROKU_API_KEY: $H_API_KEY
              HEROKU_APP_NAME: $H_APP_NAME
              ZIP_FILE: frontend/frontend-app.tar.gz
              WAIT: 'true'
              DEBUG: 'true'